version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell

formatters:
  enable:
    - gofmt

linters-settings:
  gofmt:
    simplify: true

issues:
  exclude-dirs:
    - frontend
    - node_modules

run:
  timeout: 5m
